# Generated by Django 4.0.2 on 2022-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
